### ISSUE TITLE
SyntaxError: Unexpected token '?'

### ISSUE THREAD

**Issue by toabhishekverma** [judygab/chatgpt-api-react#2]
Getting following syntax error. I can guess that this might be npm version issue. But I am not a npm developer , just trying to run this. If anyone can help.

npm run dev

> chatgpt-api@0.1.0 dev
> next dev

/home/abhishek/Repository/chatgpt-api-react/node_modules/next/dist/cli/next-dev.js:362
            showAll: args["--show-all"] ?? false,
                                         ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.dev (/home/abhishek/Repository/chatgpt-api-react/node_modules/next/dist/lib/commands.js:10:30)
    at Object.<anonymous> (/home/abhishek/Repository/chatgpt-api-react/node_modules/next/dist/bin/next:141:28)
    at Module._compile (internal/modules/cjs/loader.js:999:30)

**Comment by toabhishekverma** [comment]
Asked chat gpt and got the following answer 
Based on the error message you provided, it looks like you're encountering a syntax error related to the nullish coalescing operator (??). The error occurs in the next-dev.js file of your chatgpt-api project, which is part of the Next.js framework.

The nullish coalescing operator (??) is a feature introduced in ECMAScript 2020 (ES11) that allows you to provide a default value when a variable is null or undefined. However, it seems that the version of Node.js or the JavaScript runtime environment you're using may not support this feature.

To fix this issue, you can do one of the following:

Upgrade Node.js and/or your JavaScript runtime environment to a version that supports ECMAScript 2020 (ES11) or later, which includes support for the nullish coalescing operator (??).
Replace the nullish coalescing operator (??) with an alternative approach, such as using a conditional (ternary) operator or the logical OR (||) operator, depending on the logic you want to achieve.
Here's an example of how you can replace the nullish coalescing operator (??) with a conditional (ternary) operator:

Change:

javascript
Copy code
showAll: args["--show-all"] ?? false,
To:

javascript
Copy code
showAll: args["--show-all"] !== undefined ? args["--show-all"] : false,
Or with the logical OR (||) operator:

javascript
Copy code
showAll: args["--show-all"] || false,
Make sure to test your changes thoroughly to ensure they're working as expected in your specific use case.

**Comment by toabhishekverma** [comment]
when trying to fix the error, same syntax is used many places in code. 
Tried to install new version of nodejs and having conflict with 100 of libraries. Never ending story. 
As of now giving up with this. May try later when I have more time.
In mean time anyone has better solution please let me know. I guess a docker setup will be  best fit as its guarantee running the project , as long as docker version is satisfied.
